# Created using wingetcreate 1.0.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: ThioJoe.YTSpammerPurge
PackageVersion: 2.16.9
PackageLocale: en-US
Publisher: ThioJoe
PackageName: YT Spammer Purge
License: GNU General Public License
Copyright: © ThioJoe. GPL-3.0 License.
ShortDescription: Allows you to filter and search for spammer comments on your channel and other's YOUTUBE channel(s) in many different ways AND delete/report them all at once.
ManifestType: defaultLocale
ManifestVersion: 1.1.0

